[project]
name = "bluebikes-busiest-day-2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hvplot>=0.11.3",
    "pandas>=2.2.3",
    "panel>=1.6.3",
    "pyarrow>=20.0.0",
    "scikit-learn>=1.6.1",
]
